# Generated by Django 6.0.2 on 2026-02-15 21:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='librarylog',
            options={'ordering': ['-entry_time'], 'verbose_name': 'Library Log', 'verbose_name_plural': 'Library Logs'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='returned',
            field=models.BooleanField(default=False, help_text='Has the book been returned?'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(help_text='Unique barcode ID for the book.', max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Book ID must contain only alphanumeric characters, hyphens, or underscores.', regex='^[A-Za-z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='current_holder',
            field=models.ForeignKey(blank=True, help_text='Student who currently holds this book.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_books', to='management.student'),
        ),
        migrations.AlterField(
            model_name='librarylog',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='librarylog',
            name='exit_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='librarylog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_logs', to='management.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_id',
            field=models.CharField(help_text='Unique barcode/enrollment ID for the student.', max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Enrollment ID must contain only alphanumeric characters, hyphens, or underscores.', regex='^[A-Za-z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='management.book'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='management.student'),
        ),
        migrations.AddIndex(
            model_name='librarylog',
            index=models.Index(fields=['student', 'exit_time'], name='idx_student_exit'),
        ),
    ]
