# Generated by Django 6.0.2 on 2026-02-15 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(default='0000000000', help_text='10-digit mobile number', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
