# Generated by Django 6.0.2 on 2026-02-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_student_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Computer', 'Computer'), ('EC', 'EC'), ('Civil', 'Civil'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical')], max_length=100),
        ),
    ]
