# Generated by Django 6.0.2 on 2026-02-20 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(help_text='Unique barcode/Access Code for the book.', max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Access Code must contain only alphanumeric characters, hyphens, or underscores.', regex='^[A-Za-z0-9_-]+$')], verbose_name='Access Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_id',
            field=models.CharField(help_text='Unique barcode/enrollment ID for the student.', max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Enrollment ID must 12 digit no ', regex='^[0-9]+$')]),
        ),
    ]
