# Generated by Django 6.0.2 on 2026-02-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_book_author_alter_book_book_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
    ]
