# Generated by Django 6.0.2 on 2026-02-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_student_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='access_code',
        ),
    ]
