# Generated by Django 6.0.2 on 2026-03-26 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_book_id_to_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('transaction', models.ForeignKey(help_text='The active issue transaction to be renewed.', on_delete=django.db.models.deletion.CASCADE, related_name='renew_requests', to='management.transaction')),
            ],
            options={
                'verbose_name': 'Renew Request',
                'verbose_name_plural': 'Renew Requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
