# Generated by Django 6.0.2 on 2026-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_renewrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualReminderProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Manual Due Reminders',
                'managed': False,
            },
        ),
    ]
