# Generated by Django 6.0.2 on 2026-08-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_manualreminderproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='allocated_department',
            field=models.CharField(blank=True, choices=[('Computer', 'Computer'), ('EC', 'EC'), ('Civil', 'Civil'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN No'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Pages'),
        ),
    ]
